options:
  calico-node-image:
    type: string
    # Please refer to layer-canal/versioning.md before changing the version below.
    default: quay.io/tigera/cnx-node:v2.2.1
    description: |
      The image id to use for calico/node.
  calico-policy-image:
    type: string
    default: quay.io/tigera/kube-controllers:v2.2.1
    description: |
      The image id to use for calico/kube-controllers.
  ipip:
    type: string
    default: Never
    description: |
      IPIP mode. Must be one of "Always", "CrossSubnet", or "Never".
  nat-outgoing:
    type: boolean
    default: true
    description: |
      NAT outgoing traffic
  registry-credentials:
    type: string
    default: ""
    description: |
      Private docker registry credentials, in the form of a base64-encoded
      docker config.json file. Example:

      juju config tigera-ee registry-credentials=$(base64 -w0 config.json)
  license-key:
    type: string
    default: ""
    description: |
      Tigera EE license key, base64-encoded. Example:

      juju config tigera-ee license-key=$(base64 -w0 license.yaml)
  enable-elasticsearch-operator:
    type: boolean
    default: true
    description: |
      Enable deployment of elasticsearch-operator into Kubernetes. This
      provides a monitoring and metrics solution for use with Tigera EE that
      is suitable for proof-of-concept purposes, but is not recommended for
      production use.
